version: "3.8"

services:
  rent-site-production:
    image: rent-site-production
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NODE_ENV: .production
    environment:
      - NODE_ENV=production
    ports:
      - "3030:3000"
    restart: always

  rent-site-test:
    image: rent-site-test
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NODE_ENV: .test
    environment:
      - NODE_ENV=test
    ports:
      - 3040:3000
    restart: always
